/**
 * Single source of truth for Column Mapping (Excel Letter <-> JS Field Key)
 */

export const COL_MAP = {
  B: 'cat',
  C: 'type',
  D: 'kode',
  E: 'tpk',
  F: 'no',
  G: 'opt',
  H: 'komp',
  I: 'p',
  J: 'l',
  K: 't',
  L: 'sub',
  M: 'jml',
  N: 'bhn',
  O: 't_bhn',
  P: 'l_fin',
  Q: 'd_fin',
  R: 'p1',
  S: 'p2',
  T: 'l1',
  U: 'l2',
  V: 'lap_luar',
  W: 't_luar',
  X: 'lap_dalam',
  Y: 't_dalam',
  Z: 'edg_p1',
  AA: 'edg_p2',
  AB: 'edg_l1',
  AC: 'edg_l2',
  
  // EXTRA_COLUMNS (AD to CB)
  AD: 'profil3',
  AE: 'profil2',
  AF: 'profil',
  AG: 'siku_joint',
  AH: 'screw_jf',
  AI: 'dormec',
  AJ: 'rel',
  AK: 'engsel',
  AL: 'v',
  AM: 'v2',
  AN: 'h',
  AO: 'anodize',
  AP: 'p_val',
  AQ: 'q_anodize',
  AR: 'x_sep',
  AS: 'v_lap',
  AT: 'v_edg',
  AU: 'desc_lap',
  AV: 'desc_edg',
  AW: 'desc_komp',
  AX: 'nama_komp',
  AY: 'x_sep2',
  AZ: 'minifix',
  BA: 'dowel',
  BB: 'q_siku',
  BC: 'q_screw',
  BD: 'q_dormec_total',
  BE: 'q_engsel_total',
  BF: 'q_rel_total',
  BG: 'p_gross',
  BH: 'l_gross',
  BI: 'keliling',
  BJ: 'luas_gross',
  BK: 'bhn_dasar',
  BL: 'bhn_desc',
  BM: 'prop_harga',
  BN: 'q_anodize_std',
  BO: 'q_minifix_total',
  BP: 'q_dowel_total',
  BQ: 'q_siku_total',
  BR: 'q_screw_total',
  BS: 'area_m2',
  BT: 'vol_m3',
  BU: 't_p1',
  BV: 't_p2',
  BW: 't_l1',
  BX: 't_l2',
  BY: 'p_cnc',
  BZ: 'l_cnc',
  CA: 'ukuran_cnc',
  CB: 'csv_format'
};

export const REV_COL_MAP = Object.fromEntries(
  Object.entries(COL_MAP).map(([k, v]) => [v, k])
);

export const getColLetter = (fieldKey) => REV_COL_MAP[fieldKey] || fieldKey.toUpperCase();
