export const defaultSpekVals = {
  "Spesifikasi Produk||Bahan Kabinet 1": "Ply",
  "Spesifikasi Produk||Bahan Kabinet 2": "Ply+mdf hijau 1mk",
  "Spesifikasi Produk||Bahan Kabinet 3": "Ply+mdf hijau 2mk",
  "Spesifikasi Produk||Bahan Kabinet 4": "Mdf hijau",
  "Spesifikasi Produk||Bahan Kabinet 5": "Ply",
  "Spesifikasi Produk||Bahan Kabinet 6": "UPVC",
  "Spesifikasi Produk||Bahan Kabinet 7": "Ply Bending",
  "Spesifikasi Produk||Bahan Kabinet 8": "Blockboard",

  "Spesifikasi tebal bahan||Komponen kabinet": "18",
  "Spesifikasi tebal bahan||Komponen laci": "12",
  "Spesifikasi tebal bahan||Dinding blk / dasar": "6",
  "Spesifikasi tebal bahan||Tatakan S/s": "18",
  "Spesifikasi tebal bahan||Tatakan worktop": "27",

  "Lapisan Standard||Lapisan dibalik pintu": "HB_41130",
  "Lapisan Standard||Lapisan tidak terlihat u/ kab.": "Polos",
  "Lapisan Standard||Lapisan depan bhn pintu mlp": "Polos",
  "Lapisan Standard||tipe lap. u/ sisi tidak terlihat": "[Aica]",

  "Spesifikasi Lapisan||kabinet1 (HPL)": "HB_41130",
  "Spesifikasi Lapisan||edgingkab1 (Edg)": "Edg_Décor_1723_B",
  "Spesifikasi Lapisan||kabinet2 (HPL)": "Aica",
  "Spesifikasi Lapisan||edgingkab2 (Edg)": "Edg_Decor_1723_B(55x1)",
  "Spesifikasi Lapisan||kabinet3 (HPL)": "Aica",
  "Spesifikasi Lapisan||edgingkab3 (Edg)": "",
  "Spesifikasi Lapisan||lapisan1 (HPL)": "WY_5216_D(V)",
  "Spesifikasi Lapisan||edging1 (Inside)": "Edg_EAW_5216_D1",
  "Spesifikasi Lapisan||lapisan2 (HPL)": "(WY_5216_D(V) rangka......+Aica)",
  "Spesifikasi Lapisan||edging2 (Inside)": "Edg_EAW_5216_D1(44x1)",
  "Spesifikasi Lapisan||lapisan3 (HPL)": "L-FA_0206_AP",
  "Spesifikasi Lapisan||edging3 (Inside)": "Edg_DSS_00206_SM",
  "Spesifikasi Lapisan||lapisan4 (HPL)": "(L-FA_0206_AP rangka......+Aica)",
  "Spesifikasi Lapisan||edging4 (Inside)": "Edg_DSS_00206_SM(45X1)",
  "Spesifikasi Lapisan||lapisan5 (HPL)": "DXO_1338_D",
  "Spesifikasi Lapisan||edging5 (Inside)": "Edg_EAP_1338_DO",
  "Spesifikasi Lapisan||lapisan6 (HPL)": "",
  "Spesifikasi Lapisan||edging6 (Inside)": "Edg_Decor_2023_B",
  "Spesifikasi Lapisan||lapisan7 (HPL)": "Duco",
  "Spesifikasi Lapisan||edging7 (Inside)": "Melanor",

  "Spesifikasi komp. Anodize||trim_21": "Trim 21 S2/S4 Brown Doff ( Alm. 75181 ) P3",
  "Spesifikasi komp. Anodize||trim_22": "Trim 22 S2/S4 Brown Doff ( Alm. 75270 ) P3",
  "Spesifikasi komp. Anodize||trim_38": "ST-36 Brown Doff ( Alm. 2351 ) P3 P3",
  "Spesifikasi komp. Anodize||mled_02": "M-LED-02 Brown Doff ( Alm. 75111 ) P3",
  "Spesifikasi komp. Anodize||mprf_01": "M-PRF-01 Brown Doff ( Alm. 75110 ) P3",
  "Spesifikasi komp. Anodize||mlis_01": "M-LIST-01 Brown Doff ( Alm. 75112 ) P3",
  "Spesifikasi komp. Anodize||lis_kaca": "List Kaca Black Doff ( Alm. 6600/6599 ) P2.8",
  "Spesifikasi komp. Anodize||M_PLT_01": "M-PLT-01 Brown Doff ( Alm. 75256 ) P3",
  "Spesifikasi komp. Anodize||M_PLT_02": "M-PLT-02 Brown Doff ( Alm. 85830 ) P3",
  "Spesifikasi komp. Anodize||MH_02 (Standard)": "MH-02 Brown Doff ( Alm. 86706 ) P3",
  "Spesifikasi komp. Anodize||MH_02 (Coak Standard)": "MH-02 Brown Doff ( Alm. 86706 ) P3 coak standart",
  "Spesifikasi komp. Anodize||MH_02 (Coak Khusus)": "MH-02 Brown Doff ( Alm. 86706 ) P3 coak khusus",
  "Spesifikasi komp. Anodize||MH_08 (Black Gloss)": "MH-08 Brown Doff ( Alm. 75289 ) P3",
  "Spesifikasi komp. Anodize||MH_07 (Black)": "MH-07 Brown Doff ( Alm. 75272 ) P3",
  "Spesifikasi komp. Anodize||MH_04 (Standard)": "MH-04 Black ( Alm. 86705 ) P3",
  "Spesifikasi komp. Anodize||MH_04 (Coak Standard)": "MH-04 Black ( Alm. 86705 ) P3 coak standart",
  "Spesifikasi komp. Anodize||MH_04 (Coak Khusus)": "MH-04 Black ( Alm. 86705 ) P3 coak khusus",
  "Spesifikasi komp. Anodize||MH_03B (Standard)": "MH-09 A Brown Doff ( Alm. 75301 ) P3",
  "Spesifikasi komp. Anodize||MH_03B (Alt)": "MH-09 B Brown Doff ( Alm. MF 75303 R ) P3",
  "Spesifikasi komp. Anodize||edging7 (trimpanel)": "Trim 21 S2/S4 Brown Doff ( Alm. 75181 ) P3",
  "Spesifikasi komp. Anodize||edging8 (trimkaca)": "Trim 22 S2/S4 Brown Doff ( Alm. 75270 ) P3",
  "Spesifikasi komp. Anodize||edging9": "ST-36 Brown Doff ( Alm. 2351 ) P3 P3",

  "Spesifikasi frame Alu||M_FRM Tutup Belakang": "M-FRM Tutup Belakang Brown Doff ( Alm. 75225 ) P3",
  "Spesifikasi frame Alu||M_FRM": "M-FRM Body Brown Doff ( Alm. 75226 ) P3",
  "Spesifikasi frame Alu||M_FRM-07": "M-FRM-07 Brown Doff ( Alm. 75355 ) P3",
  "Spesifikasi frame Alu||M_FRM-02": "M-FRM-02 Black Doff ( Alm. 75227 ) P3",
  "Spesifikasi frame Alu||M_FRM-03": "M-FRM-03 Black Doff ( Alm. 75229 ) P3",
  "Spesifikasi frame Alu||M_SHF-01/02": "M-SHF-01/02 Brown Doff ( Alm. 75109 ) P3",
  "Spesifikasi frame Alu||LS_01": "LS-01 Brown Doff ( Alm. 86599 ) P3",
  "Spesifikasi frame Alu||M_FRM-05||fr7": "Alm. 75283 ( M-FRM-05 ) MENTAH P6",
  "Spesifikasi frame Alu||M_FRM-05||fr8": "Alm. 75284 ( M-FRM-05 ) MENTAH P6",
  "Spesifikasi frame Alu||Mullion Luar": "Mullion Luar Black Doff ( Alm. 75114 ) P3",
  "Spesifikasi frame Alu||Mullion Dalam": "Mullion Dalam Black Doff ( Alm. 41316 ) P3",
  "Spesifikasi frame Alu||Mullion M Frame 07": "Alm. 75354 ( Mulion M-FRM-07 ) CA1 P6",
  "Spesifikasi frame Alu||LS_02": "LS-02 Black Gloss ( Alm. 10321 ) P3",
  "Spesifikasi frame Alu||Mullion Dalam (1)": "Mullion Dalam Black Doff ( Alm. 41316 ) P3",
  "Spesifikasi frame Alu||Mullion Dalam (2)": "Mullion Dalam Mocha Gloss ( Alm. 41316 ) P3",

  "Spesifikasi Engsel||engsel_pantry||engsel1": "ENGSEL CLIP TOP 107 DEG INTEGRATED 75 B 1550 + 173 L 6100",
  "Spesifikasi Engsel||engsel_pantry||engsel2": "ENGSEL SALICE PUSH.TIP ON FOR DOOR",
  "Spesifikasi Engsel||engsel_pantry||engsel3": "ENGSEL 155 DRAJAT 71 B 7550",
  "Spesifikasi Engsel||engsel_pantry||engsel4": "ENGSEL BIFOLD",
  "Spesifikasi Engsel||engsel_pantry||engsel5": "ENGSEL 79M9550 BLIND CORNER",
  "Spesifikasi Engsel||engsel_wrd||engsel6": "ENGSEL S 8657i B12 TH52",
  "Spesifikasi Engsel||engsel_wrd||engsel7": "ENGSEL 9936 W45 C6",
  "Spesifikasi Engsel||engsel_wrd||engsel8": "Engsel Sensys Full Bengkok C 16-110 DERAJAT 907 1207",
  "Spesifikasi Engsel||engsel_wrd||engsel9": "ENGSEL MEPLA FLAP DOOR",
  "Spesifikasi Engsel||": "RDK-52A FOLDING HINGE",

  "Spesifikasi Rel laci||Legrabox||rel1": "LEGRA S1 ORION GREY (OG",
  "Spesifikasi Rel laci||Legrabox||rel2": "LEGRABOX S4 OG (ORION GREY)",
  "Spesifikasi Rel laci||Rel_Pantry||rel3": "REL TANDEM BLUM SINGLE EXT INTG P.500",
  "Spesifikasi Rel laci||Rel_Pantry||rel4": "REL TANDEM BLUM FULL EXT INTG P.500",
  "Spesifikasi Rel laci||Rel_Pantry||rel5": "REL TANDEM BLUM FULL EXT INTG P.400",
  "Spesifikasi Rel laci||Tandembox||rel6": "LACI B1S1 INTE BLUMO",
  "Spesifikasi Rel laci||Tandembox||rel7": "B1S2 GREY INTEG.BM",
  "Spesifikasi Rel laci||Rel_Pantry||rel8": "REL TANDEM BLUM SINGLE EXT INTG P.450",
  "Spesifikasi Rel laci||Merivobox||rel9": "MERIVOBOX MVX S1 SW 500 40 BM",
  "Spesifikasi Rel laci||Merivobox||rel10": "MERIVOBOX MVX S4 SW 500 70 BM",
  "Spesifikasi Rel laci||Merivobox||rel11": "LACI MERIVOBOX S2 + KACA ORION GREY",
  "Spesifikasi Rel laci||Rel_wrd": "QUADRO V6 SFP FL 500 EB 20 TIP ON HETTICH L/R",
  "Spesifikasi Rel laci||Avantech": "Avantech You 101 P.500mm",
  "Spesifikasi Rel laci||Rel Laci 14": "Avantech You 251 P.500mm",

  "Spesifikasi Door Mechanism||Pocket Door 55 cm": "Pocket Door 55 cm",
  "Spesifikasi Door Mechanism||Aventos 1": "-",
  "Spesifikasi Door Mechanism||Aventos 2": "-",
  "Spesifikasi Door Mechanism||Aventos 3": "-",

  "Spesifikasi Kaca||Kaca type 1": "MG_Coklat_Susu",
  "Spesifikasi Kaca||Kaca type 2": "Euro_Grey",
  "Spesifikasi Kaca||Kaca type 3": "Polos",
  "Spesifikasi Kaca||Kaca type 4": "MG_Purewhite",
  "Spesifikasi Kaca||Kaca type 5": "Bronze",
  "Spesifikasi Kaca||Kaca type 6": "Grey_Tinted",
  "Spesifikasi Kaca||Kaca type 7": "Polos",
  "Spesifikasi Kaca||Kaca type 8": "Moru↔",
  "Spesifikasi Kaca||Kaca type 9": "Acid_Clear",
  "Spesifikasi Kaca||Kaca type 10": "Polos",
  "Spesifikasi Kaca||Kaca type 11": "Polos",

  "Spesifikasi Profil||MR_02||prof_pintu_1": "PROFIL R5 MDF hijau 10X15X2350 (MR 02)",
  "Spesifikasi Profil||MLP_04": "PROFIL MLP 04 MDF HIJAU UK 2350X14X14",
  "Spesifikasi Profil||MLP_02||prof_pintu_3": "PROFIL MLP 02 MDF HIJAU UK 2350X16X17( Tidak coak)",
  "Spesifikasi Profil||PT_04": "PROFIL PT-04 MDF HIJAU P.2440",
  "Spesifikasi Profil||PIRAMID": "PROFIL KOTAK PIRAMID 4X4",
  "Spesifikasi Profil||MLP_02||prof_panel_3": "PROFIL MLP 02 MDF HIJAU UK 2350X16X17( Tidak coak)",
  "Spesifikasi Profil||MLT_01": "PROFIL MLT 01 MDF + PLY 2440X128X24",
  "Spesifikasi Profil||MR_02||prof_cor_2": "PROFIL R5 MDF hijau 10X15X2350 (MR 02)",
  "Spesifikasi Profil||MR_02||prof_cor_3": "PROFIL R5 MDF hijau 10X15X2350 (MR 02)",
  "Spesifikasi Profil||MPP_01||prof_pl_1": "PROFIL PLINT MPP-01 T.100  MDF HIJAU UK:2350x100x45",
  "Spesifikasi Profil||MPP_01||prof_pl_2": "PROFIL PLINT MPP-01 T.100  MDF HIJAU",
  "Spesifikasi Profil||MPP_01||prof_pl_3": "PROFIL PLINT MPP-01 T.100  MDF HIJAU",

  "Referensi jarak/ukuran||nat pintu 1 sisi": "1.5",
  "Referensi jarak/ukuran||tebal cover panel/pelmet": "19",
  "Referensi jarak/ukuran||nat antara pintu FC dg worktop": "30",
  "Referensi jarak/ukuran||jarak ram standart 1": "50",
  "Referensi jarak/ukuran||jarak ram standart 2": "80",
  "Referensi jarak/ukuran||toleransi pengurangan dinding samping": "0",
  "Referensi jarak/ukuran||jarak plinth masuk": "0",
  "Referensi jarak/ukuran||Jarak pintu overlap atas": "0",
  "Referensi jarak/ukuran||Jarak pintu overlap bawah": "0",
};
