export const defaultSpekVals = {
  "Spesifikasi Produk||Bahan Kabinet 1": "Ply",
  "Spesifikasi Produk||Bahan Kabinet 2": "Ply+mdf hijau 1mk",
  "Spesifikasi Produk||Bahan Kabinet 3": "Ply+mdf hijau 2mk",
  "Spesifikasi Produk||Bahan Kabinet 4": "Mdf hijau",
  "Spesifikasi Produk||Bahan Kabinet 5": "Ply",
  "Spesifikasi Produk||Bahan Kabinet 6": "UPVC",
  "Spesifikasi Produk||Bahan Kabinet 7": "Ply Bending",
  "Spesifikasi tebal bahan||Komponen kabinet": "18",
  "Spesifikasi tebal bahan||Komponen laci": "12",
  "Spesifikasi tebal bahan||Dinding blk / dasar": "6",
  "Spesifikasi tebal bahan||Tatakan S/s": "18",
  "Spesifikasi tebal bahan||Tatakan worktop": "9",
  "Spesifikasi Lapisan / Fin.||Lapisan dibalik pintu": "HB_41130",
  "Spesifikasi Lapisan / Fin.||Lapisan tidak terlihat u/ kab.": "Polos",
  "Spesifikasi Lapisan / Fin.||Lapisan depan bhn pintu mlp": "Polos",
  "Spesifikasi Lapisan / Fin.||tipe lap. u/ sisi tidak terlihat": "[Aica]",
  "Spesifikasi komp. Anodize||trim_21": "Trim 21 S2/S4 Black Doff ( Alm. 75181 ) P3",
  "Spesifikasi komp. Anodize||trim_22": "Trim 22 S2/S4 Black Doff ( Alm. 75270 ) P3",
  "Spesifikasi komp. Anodize||trim_38": "ST-36 Black Doff ( Alm. 2351 ) P3 P3",
  "Spesifikasi komp. Anodize||mled_02": "M-LED-02 Black Doff ( Alm. 75111 ) P3",
  "Spesifikasi komp. Anodize||mprf_01": "M-PRF-01 Black Doff ( Alm. 75110 ) P3",
  "Spesifikasi komp. Anodize||mlis_01": "M-LIST-01 Black Doff ( Alm. 75112 ) P3",
  "Spesifikasi komp. Anodize||lis_kaca": "List Kaca Black Doff ( Alm. 6600/6599 ) P2.8",
  "Spesifikasi komp. Anodize||M_PLT_01": "M-PLT-01 Black Doff ( Alm. 75256 ) P3",
  "Spesifikasi komp. Anodize||M_PLT_02": "M-PLT-02 Black Doff ( Alm. 85830 ) P3",
  "Spesifikasi komp. Anodize||MH_02 (Coak Khusus)": "MH-02 Black Doff ( Alm. 86706 ) P3 coak khusus",
  "Spesifikasi komp. Anodize||MH_08 (Black Gloss)": "MH-08 Black Gloss ( Alm. 75289 ) P3",
  "Spesifikasi komp. Anodize||MH_07 (Black)": "MH-07 Black ( Alm. 75272 ) P3",
  "Spesifikasi komp. Anodize||MH_04 (Coak Khusus)": "MH-04 Black ( Alm. 86705 ) P3 coak khusus",
  "Spesifikasi komp. Anodize||MH_03B (Standard)": "MH-03B Black Doff ( Alm. 75117 ) P3",
  "Spesifikasi frame Alu||M_FRM Tutup Belakang": "M-FRM Tutup Belakang Black Doff ( Alm. 75225 ) P3",
  "Spesifikasi frame Alu||M_FRM Body": "M-FRM Body Black Doff ( Alm. 75226 ) P3",
  "Spesifikasi frame Alu||M_FRM-07": "M-FRM-07 Black Doff ( Alm. 75355 ) P3",
  "Spesifikasi frame Alu||M_FRM-02": "M-FRM-02 Black Doff ( Alm. 75227 ) P3",
  "Spesifikasi frame Alu||M_FRM-03": "M-FRM-03 Brown Gloss ( Alm. 75229 ) P3",
  "Spesifikasi frame Alu||M_SHF-01/02": "M-SHF-01/02 Brown Gloss ( Alm. 75109 ) P3",
  "Spesifikasi frame Alu||LS_01": "LS-01 Black Gloss ( Alm. 86599 ) P3",
  "Spesifikasi frame Alu||Alm. 75283": "Alm. 75284 ( M-FRM-05 ) MENTAH P6",
  "Spesifikasi frame Alu||Mullion Luar": "Mullion Luar Black Doff ( Alm. 75114 ) P3",
  "Spesifikasi frame Alu||Mullion Dalam": "Mullion Dalam Mocha Gloss ( Alm. 41316 ) P3",
  "Spesifikasi frame Alu||Alm. 75354": "Alm. 75354 ( Mulion M-FRM-07 ) CA1 P6",
  "Spesifikasi frame Alu||LS_02": "LS-02 Black Gloss ( Alm. 10321 ) P3",
  "Spesifikasi Engsel||engsel pintu tebal": "ENGSEL PROFILE TEBAL PINTU 24 MM 71 B 9550 + 173 L 6100",
  "Spesifikasi Engsel||engsel pintu wrd": "Engsel Sensys Full Bengkok C 16-110 DERAJAT 907 1207",
  "Spesifikasi Rel laci||Rel Laci 1": "LEGRABOX I6 ORION GREY",
  "Spesifikasi Rel laci||Rel Laci 2": "REL TANDEM BLUM SINGLE EXT INTG P.450",
  "Spesifikasi Rel laci||Rel Laci 3": "LACI B1S4 INTEGRATED",
  "Spesifikasi Rel laci||Rel Laci 4": "QUADRO V6 SFD FL 350 L/R",
  "Spesifikasi Rel laci||Rel Laci 5": "MERIVOBOX MVX S4XL SW 500 70 BM",
  "Spesifikasi Door Mechanism||Aventos 1": "-",
  "Spesifikasi Kaca||Kaca type 1": "MG_Coklat_Susu",
  "Spesifikasi Kaca||Kaca type 2": "Euro_Grey",
  "Spesifikasi Kaca||Kaca type 3": "Polos",
  "Spesifikasi Kaca||Kaca type 4": "MG_Purewhite",
  "Spesifikasi Kaca||Kaca type 5": "Bronze",
  "Spesifikasi Kaca||Kaca type 6": "Grey_Tinted",
  "Spesifikasi Kaca||Kaca type 7": "Polos",
  "Spesifikasi Kaca||Kaca type 8": "Moru↔",
  "Spesifikasi Kaca||Kaca type 9": "Acid_Clear",
  "Spesifikasi Profil||prof_pintu_1 (MR 02)": "PROFIL R5 MDF hijau 10X15X2350 (MR 02)",
  "Spesifikasi Profil||prof_pintu_3 (MLP 06)": "PROFIL MLP 06 MDF HIJAU P. 2440",
  "Spesifikasi Profil||prof_panel_1 (PB 25)": "PROFIL BULAT MDF HIJAU (PB25) P.2440",
  "Spesifikasi Profil||prof_panel_3 (MLP 02)": "PROFIL MLP 02 MDF HIJAU UK 2350X16X17( Tidak coak)",
  "Spesifikasi Profil||prof_cor_1 (MLT 01)": "PROFIL MLT 01 MDF + PLY 2440X128X24",
  "Spesifikasi Profil||prof_pl_1 (MPP_01)": "PROFIL PLINT MPP-01 T.100  MDF HIJAU",
  "Referensi jarak/ukuran||nat pintu 1 sisi": "1.5",
  "Referensi jarak/ukuran||tebal cover panel/pelmet": "19",
  "Referensi jarak/ukuran||nat antara pintu FC dg worktop": "30",
  "Referensi jarak/ukuran||jarak ram standart 1": "50",
  "Referensi jarak/ukuran||jarak ram standart 2": "80",
  "Referensi jarak/ukuran||toleransi pengurangan dinding samping": "0",
  "Referensi jarak/ukuran||jarak plinth masuk": "0",
  "Referensi jarak/ukuran||Jarak pintu overlap atas": "0",
  "Referensi jarak/ukuran||Jarak pintu overlap bawah": "0",
};
